name: RPM Build
on:
  push:
    tags:
      - "*.*.*"

env:
  DIST: fc42
  ARCH: x86_64

jobs:
  build_rpm:
    runs-on: ubuntu-latest
    container:
      image: fedora:42
    steps:
      - uses: actions/checkout@v5
      - name: Install rpmdevtools
        run: sudo dnf install -y rpmdevtools
      - name: Build rpm package
        run: rpmbuild --define "_topdir $(pwd)" -bb SPECS/epiclang.spec
      - name: Upload .rpm package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: epiclang-${{ github.ref_name }}-1.${{ env.DIST }}.${{ env.ARCH }}.rpm
          path: RPMS/${{ env.ARCH }}/*.rpm
      
  release:
    name: Create release with rpm package
    needs: build_rpm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: epiclang-${{ github.ref_name }}-1.${{ env.DIST }}.${{ env.ARCH }}.rpm/**/*.rpm
