name: RPM Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:42
    steps:
      - uses: actions/checkout@v4
      - name: Install depencies
        run: sudo dnf install -y rpmdevtools
      - name: build rpm package
        run: rpmbuild --define "_topdir $(pwd)" -bb SPECS/epiclang.spec
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: RPMS/x86_64/epiclang-1.0.0-1.fc42.x86_64.rpm 
          #asset_name: mything
          tag: 1.0.0
          overwrite: true
          body: ""

