name: RPM Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:42
    steps:
      - uses: actions/checkout@v4
      - name: Install depencies
        run: sudo dnf install -y rpmdevtools
      - name: build rpm package
        run: rpmbuild --define "_topdir $(pwd)" -bb SPECS/epiclang.spec
      - name: Release the Package
        uses: softprops/action-gh-release@v1
        with:
          files: RPMS/x86_64/epiclang-1.0.0-1.fc42.x86_64.rpm

