name: RPM Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: fedora:42
    steps:
      - uses: actions/checkout@v4
      - name: Install depencies
        run: sudo dnf install -y rpmdevtools
      - name: build rpm package
        run: rpmbuild -bb ./SPECS/epiclang.spec

