name: RPM Build
on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
      name: Create release with rpm package
      needs: build_rpm
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v5
        - name: Download rpm artifact
          uses: actions/download-artifact@v5
          with:
            name: |
              epiclang-${{ env.VERSION }}-1.${{ env.DIST }}.${{ env.ARCH }}.rpm
              epiclang-plugin-banana-${{ env.VERSION }}-1.${{ env.DIST }}.${{ env.ARCH }}.rpm
        - name: Create release
          uses: softprops/action-gh-release@v2
          if: github.ref_type == 'tag'
          with:
            files: |
              epiclang-${{ env.VERSION }}-1.${{ env.DIST }}.${{ env.ARCH }}.rpm
              epiclang-plugin-banana-${{ env.VERSION }}-1.${{ env.DIST }}.${{ env.ARCH }}.rpm
            token: ${{ secrets.RELEASE}}
